# Generated by Django 5.0 on 2025-10-03 22:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='voters',
            field=models.ManyToManyField(blank=True, related_name='petition_votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
